QBShared = QBShared or {}
QBShared.Vehicles = {	
-- NHS
	['ambulance'] = {-- NHS
		['name'] = 'Ambulance',
		['brand'] = 'NHS',
		['model'] = 'ambulance',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `ambulance`,
		['shop'] = 'nhs',
	},
	['nhsx51'] = {-- NHS
		['name'] = 'BMW X5',
		['brand'] = 'NHS',
		['model'] = 'nhsx51',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nhsx51`,
		['shop'] = 'nhs',
	},
	['nhsmr'] = {-- NHS
		['name'] = 'Land Rover Defender',
		['brand'] = 'NHS',
		['model'] = 'nhsmr',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nhsmr`,
		['shop'] = 'nhs',
	},
	['skodanhs'] = {-- NHS
		['name'] = 'Skoda',
		['brand'] = 'NHS',
		['model'] = 'skodanhs',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `skodanhs`,
		['shop'] = 'nhs',
	},
	['hart1'] = {-- NHS
		['name'] = 'Mercedes Sprinter Van',
		['brand'] = 'NHS',
		['model'] = 'hart1',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `hart1`,
		['shop'] = 'nhs',
		},
	['lrdnhs'] = {-- NHS
		['name'] = 'NHS Land Rover Defender',
		['brand'] = 'NHS',
		['model'] = 'lrdnhs',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `lrdnhs`,
		['shop'] = 'nhs',
	},
	['els_imprez_NHS'] = { --NHS
		['name'] = 'NHS Impreza',
		['brand'] = 'NHS',
		['model'] = 'els_imprez_NHS',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `els_imprez_NHS`,
		['shop'] = 'nhs',
    },
    ['nissantitan17'] = { --NHS
		['name'] = 'NHS Nissan Titan',
		['brand'] = 'NHS',
		['model'] = 'nissantitan17',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nissantitan17`,
		['shop'] = 'nhs',
    },
    ['marked_skod_els_nhs'] = { --NHS
		['name'] = 'NHS Skoda',
		['brand'] = 'NHS',
		['model'] = 'marked_skod_els_nhs',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `marked_skod_els_nhs`,
		['shop'] = 'nhs',
    },
	['parabike'] = {-- NHS
		['name'] = 'BMW Bike',
		['brand'] = 'NHS',
		['model'] = 'parabike',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `parabike`,
		['shop'] = 'nhs',
	},
	['nhsxc90sar'] = {-- NHS
		['name'] = 'Volvo XC90',
		['brand'] = 'NHS',
		['model'] = 'nhsxc90sar',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nhsxc90sar`,
		['shop'] = 'nhs',
	},
	['nhsrr'] = {-- NHS
		['name'] = 'Range Rover',
		['brand'] = 'NHS',
		['model'] = 'nhsrr',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nhsrr`,
		['shop'] = 'nhs',
	},
	['nhsbmwd'] = { -- NHS
		['name'] = 'NHS BMW Estate',
		['brand'] = 'NHS',
		['model'] = 'nhsbmwd',
		['price'] =  2000,
		['category'] = 'nhs',
		['hash'] = `nhsbmwd`,
		['shop'] = 'nhs',
	},
	['nhsfpace'] = {-- NHS
		['name'] = 'NHS Jaguar',
		['brand'] = 'NHS',
		['model'] = 'nhsfpace',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nhsfpace`,
		['shop'] = 'nhs',
		},
	['nhsxc90'] = {-- NHS
		['name'] = 'NHS XC90 Command',
		['brand'] = 'NHS',
		['model'] = 'nhsxc90',
		['price'] = 2000,
		['category'] = 'nhs',
		['hash'] = `nhsxc90`,
		['shop'] = 'nhs',
	},
-- Snow
	['gritter'] = {-- Snow
		['name'] = 'Arocs Gritter',
		['brand'] = 'Snow',
		['model'] = 'gritter',
		['price'] = 100,
		['category'] = 'classzero',
		['hash'] = `gritter`,
		['shop'] = 'luxury', 
	},
	['rapsnow'] = {-- Snow
		['name'] = 'Raptor Snow Plow',
		['brand'] = 'Snow',
		['model'] = 'rapsnow',
		['price'] = 100,
		['category'] = 'classzero',
		['hash'] = `rapsnow`,
		['shop'] = 'luxury',	
	},
-- Driftworks
	['flatbedm2'] = {-- Drift Works
		['name'] = ' Drift Works Freightliner Flatbed',
		['brand'] = 'driftworks',
		['model'] = 'flatbedm2',
		['price'] = 2000,
		['category'] = 'driftworks',
		['hash'] = `flatbedm2`,
		['shop'] = 'driftworks',
	},
	['fhauler'] = {-- Drift Works
		['name'] = 'Drift Works 2013 Western Hauler M2',
		['brand'] = 'driftworks',
		['model'] = 'fhauler',
		['price'] = 2000,
		['category'] = 'driftworks',
		['hash'] = `fhauler`,
		['shop'] = 'driftworks',
	},
	['trans_mbenzarocs'] = {-- Drift Works
		['name'] = 'Drift Works Mercedes-Benz Arocs SLT',
		['brand'] = 'driftworks',
		['model'] = 'trans_mbenzarocs',
		['price'] = 2000,
		['category'] = 'driftworks',
		['hash'] = `trans_mbenzarocs`,
		['shop'] = 'driftworks',
	},
	['landseries3'] = {-- Drift Works
		['name'] = 'Drift Works Land Rover Pickup Series 3 1988 ',
		['brand'] = 'driftworks',
		['model'] = 'landseries3',
		['price'] = 2000,
		['category'] = 'driftworks',
		['hash'] = `landseries3`,
		['shop'] = 'driftworks',
	},
	['MUX'] = {-- Drift Works
		['name'] = 'Drift Works Isuzu D-MAX',
		['brand'] = 'driftworks',
		['model'] = 'MUX',
		['price'] = 2000,
		['category'] = 'driftworks',
		['hash'] = `MUX`,
		['shop'] = 'driftworks',
	},
	['L200'] = {-- Drift Works
		['name'] = 'Drift Works Mitsubishi L200 Triton 2006',
		['brand'] = 'driftworks',
		['model'] = 'L200',
		['price'] = 2000,
		['category'] = 'driftworks',
		['hash'] = `L200`,
		['shop'] = 'driftworks',
	},
-- MET
	['metbike'] = {-- Met 
		['name'] = 'Met Bike',
		['brand'] = 'Met',
		['model'] = 'metbike',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `metbike`,
		['shop'] = 'met',
	},
	['audia4p'] = {-- Met 
		['name'] = 'Met',
		['brand'] = 'Class 4',
		['model'] = 'audia4p',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `audia4p`,
		['shop'] = 'met',
	},
	['sprinterp'] = {-- Met 
		['name'] = 'Police Transit Van',
		['brand'] = 'Met',
		['model'] = 'sprinterp',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `sprinterp`,
		['shop'] = 'met',
	},
	['police'] = {-- Met 
		['name'] = 'Dog Unit Van',
		['brand'] = 'Met',
		['model'] = 'police',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `police`,
		['shop'] = 'met',
	},
	['astra_marked_els'] = {-- Met 
		['name'] = 'Marked Astra',
		['brand'] = 'Met',
		['model'] = 'astra_marked_els',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `astra_marked_els`,
		['shop'] = 'met',
    },
	['fordrappol'] = {-- Met 
		['name'] = 'Ford Raptor',
		['brand'] = 'Met',
		['model'] = 'fordrappol',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `fordrappol`,
		['shop'] = 'met',
	},
	['bmw330p'] = {-- Met 
		['name'] = 'BMW 330P Marked',
		['brand'] = 'Met',
		['model'] = 'bmw330p',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `bmw330p`,
		['shop'] = 'met',
	},
	['bmwm135ip'] = {-- Met 
		['name'] = 'BMW 135i',
		['brand'] = 'Met',
		['model'] = 'bmwm135ip',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `bmwm135ip`,
		['shop'] = 'met',
	},
	['els_imprez_marked'] = {-- Met 
		['name'] = 'Marked Impreza',
		['brand'] = 'Met',
		['model'] = 'els_imprez_marked',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `els_imprez_marked`,
		['shop'] = 'met',
	},
	['evo9_marked_els'] = {-- Met 
		['name'] = 'Marked Evo9',
		['brand'] = 'Met',
		['model'] = 'evo9_marked_els',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `evo9_marked_els`,
		['shop'] = 'met',
	},
	['focusrbun'] = {-- Met 
		['name'] = 'Unmarked Focus',
		['brand'] = 'Met',
		['model'] = 'focusrbun',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `focusrbun`,
		['shop'] = 'met',
	},
	['marked_skod_els'] = {-- Met 
		['name'] = 'Marked Skoda',
		['brand'] = 'Met',
		['model'] = 'marked_skod_els',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `marked_skod_els`,
		['shop'] = 'met',
	},
	['marked_wrx_els'] = {-- Met 
		['name'] = 'Marked WRX',
		['brand'] = 'Met',
		['model'] = 'marked_wrx_els',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `marked_wrx_els`,
		['shop'] = 'met',
	},
	['marked_x5'] = {-- Met 
		['name'] = 'Marked X5',
		['brand'] = 'Met',
		['model'] = 'marked_x5',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `marked_x5`,
		['shop'] = 'met',
	},
	['rs5_marked'] = {-- Met 
		['name'] = 'Marked RS5',
		['brand'] = 'Met',
		['model'] = 'rs5_marked',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `rs5_marked`,
		['shop'] = 'met',	
	},
	['x6munmarked'] = {-- Met 
		['name'] = 'Unmarked X6M',
		['brand'] = 'Met',
		['model'] = 'x6munmarked',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `x6munmarked`,
		['shop'] = 'met',
	},
	['rrsfc'] = {-- Met 
		['name'] = 'Marked Range Rover',
		['brand'] = 'Met',
		['model'] = 'rrsfc',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `rrsfc`,
		['shop'] = 'met',
	},
	['amgump'] = {-- Met 
		['name'] = 'Unmarked AMG Mercedes',
		['brand'] = 'Met',
		['model'] = 'amgump',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `amgump`,
		['shop'] = 'met',
	},
	['bmw5pmk'] = {-- Met 
		['name'] = 'BMW M5 Interceptor',
		['brand'] = 'Met',
		['model'] = 'bmw5pmk',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `bmw5pmk`,
		['shop'] = 'met',
	},
	['golfgtip'] = {-- Met 
		['name'] = 'Golf GTI Unmarked',
		['brand'] = 'Met',
		['model'] = 'golfgtip',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `golfgtip`,
		['shop'] = 'met',
	},
	['mercclarpu'] = {-- Met 
		['name'] = 'Mercedes Estate Interceptor',
		['brand'] = 'Met',
		['model'] = 'mercclarpu',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `mercclarpu`,
		['shop'] = 'met',
	},
	['s3rpu'] = {-- Met 
		['name'] = 'Audi S3',
		['brand'] = 'Met',
		['model'] = 's3rpu',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `s3rpu`,
		['shop'] = 'met',
	},
	['bmwm5rpu'] = {-- Met
		['name'] = 'BMW M5',
		['brand'] = 'Met',
		['model'] = 'bmwm5rpu',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `bmwm5rpu`,
		['shop'] = 'met',
	},
	['bmw540um'] = {-- Met
		['name'] = 'BMW 540 UM',
		['brand'] = 'Met',
		['model'] = 'bmw540um',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `bmw540um`,
		['shop'] = 'met',
	},
	['ARV2'] = {-- Met
		['name'] = 'BMW X5',
		['brand'] = 'Met',
		['model'] = 'ARV2',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `ARV2`,
		['shop'] = 'met',
	},
	['ARV3'] = {-- Met
		['name'] = 'BMW X5 UM',
		['brand'] = 'Met',
		['model'] = 'ARV3',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `ARV3`,
		['shop'] = 'met',
	},
	['bmw540p'] = {-- Met
		['name'] = 'Marked BMW 540i',
		['brand'] = 'Met',
		['model'] = 'bmw540p',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `bmw540p`,
		['shop'] = 'met',
	},
	['jagxfrum'] = {-- Met
		['name'] = 'Unmarked Jaguar',
		['brand'] = 'Met',
		['model'] = 'jagxfrum',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `jagxfrum`,
		['shop'] = 'met',
		},
	['rrsfcum'] = {-- Met
		['name'] = 'UM range rover',
		['brand'] = 'Met',
		['model'] = 'rrsfcum',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `rrsfcum`,
		['shop'] = 'met',
		},
	['suburap'] = {-- Met
		['name'] = 'Marked Subaru Impreza',
		['brand'] = 'Met',
		['model'] = 'suburap',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `suburap`,
		['shop'] = 'met',
		},
	['audis3um'] = {-- Met
		['name'] = 'Audi S3 unmarked',
		['brand'] = 'Met',
		['model'] = 'audis3um',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `audis3um`,
		['shop'] = 'met',
	},
	['nissangtrp'] = {-- Met
		['name'] = 'Nissan GTR',
		['brand'] = 'Met',
		['model'] = 'nissangtrp',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `nissangtrp`,
		['shop'] = 'met',
	},
	['umtesla'] = {-- Met
		['name'] = 'Tesla Model 3 UM',
		['brand'] = 'Met',
		['model'] = 'umtesla',
		['price'] =  2000,
		['category'] = 'met',
		['hash'] = `umtesla`,
		['shop'] = 'met',
    },
	['scramblerp'] = {-- Met
		['name'] = 'Scrambler Bike',
		['brand'] = 'Met',
		['model'] = 'scramblerp',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `scramblerp`,
		['shop'] = 'met',
	},
	['prisontruck'] = {-- Met
		['name'] = 'Met',
		['brand'] = 'Class 0',
		['model'] = 'prisontruck',
		['price'] = 2000,
		['category'] = 'met',
		['hash'] = `prisontruck`,
		['shop'] = 'met',
	},
-- PDM
	['GCMYARIS'] = {-- PDM
		['name'] = 'Toyota Yaris',
		['brand'] = 'Toyota',
		['model'] = 'GCMYARIS',
		['price'] = 2000,
		['category'] = 'pdm',
		['hash'] = `GCMYARIS`,
		['shop'] = 'pdm',
	},
	['gcm500e'] = {-- PDM
		['name'] = 'Fiat 500 E',
		['brand'] = 'Fiat',
		['model'] = 'gcm500e',
		['price'] = 2000,
		['category'] = 'pdm',
		['hash'] = `gcm500e`,
		['shop'] = 'pdm',
	},
	['golf4'] = {-- PDM
		['name'] = 'Golf MK4',
		['brand'] = 'Golf',
		['model'] = 'golf4',
		['price'] = 2000,
		['category'] = 'pdm',
		['hash'] = `golf4`,
		['shop'] = 'pdm',
	},
	['mk3vr6'] = {-- PDM
		['name'] = 'Golf VR6',
		['brand'] = 'Golf',
		['model'] = 'mk3vr6',
		['price'] = 2000,
		['category'] = 'pdm',
		['hash'] = `mk3vr6`,
		['shop'] = 'pdm',
	},
	['ferio'] = {-- PDM
		['name'] = '2000 Honda Civic Ferio SiR',
		['brand'] = 'Honda',
		['model'] = 'ferio',
		['price'] = 8000,
		['category'] = 'pdm',
		['hash'] = `ferio`,
		['shop'] = 'pdm',
	},  
	['rav4'] = {-- PDM
		['name'] = 'Toyota RAV',
		['brand'] = 'Toyota',
		['model'] = 'rav4',
		['price'] = 10000,
		['category'] = 'pdm',
		['hash'] = `rav4`,
		['shop'] = 'pdm',
	},          
	['caddyvw'] = {-- PDM
		['name'] = 'Volkswagen Caddy',
		['brand'] = 'Volkswagen',
		['model'] = 'caddyvw',
		['price'] = 10000,
		['category'] = 'pdm',
		['hash'] = `caddyvw`,
		['shop'] = 'pdm',
	},
	['gcmpassat12'] = {-- PDM
		['name'] = 'Volkswagen Passat',
		['brand'] = 'Volkswagen',
		['model'] = 'gcmpassat12',
		['price'] = 10000,
		['category'] = 'pdm',
		['hash'] = `gcmpassat12`,
		['shop'] = 'pdm',
	},
	['nbike'] = {-- PDM
	    ['name'] = 'Nordic Games Bike',
	    ['brand'] = 'Nordic',
	    ['model'] = 'nbike',
	    ['price'] = 10000,
	    ['category'] = 'pdm',
	    ['hash'] = `nbike`,
	    ['shop'] = 'pdm',
    },  
	['mcjcw20'] = {-- PDM
		['name'] = 'Mini JCW',
		['brand'] = 'Mini',
		['model'] = 'mcjcw20',
		['price'] = 12000,
		['category'] = 'pdm',
		['hash'] = `mcjcw20`,
		['shop'] = 'pdm',
	},
	['ek9'] = {-- PDM
		['name'] = 'Honda Civic EK9',
		['brand'] = 'Honda',
		['model'] = 'ek9',
		['price'] = 12000,
		['category'] = 'pdm',
		['hash'] = `ek9`,
		['shop'] = 'pdm',
	},
	['fe86'] = {-- PDM
		['name'] = 'Ford Escort RS Turbo',
		['brand'] = 'Ford',
		['model'] = 'fe86',
		['price'] = 15000,
		['category'] = 'pdm',
		['hash'] = `fe86`,
		['shop'] = 'pdm',
	},    
	['mk1rabbit'] = {-- PDM
	    ['name'] = 'MK1 Golf',
	    ['brand'] = 'Golf',
	    ['model'] = 'mk1rabbit',
	    ['price'] = 20000,
	    ['category'] = 'pdm',
	    ['hash'] = `mk1rabbit`,
	    ['shop'] = 'pdm',
    },
	['m3s'] = {-- PDM
		['name'] = 'BMW 320D',
		['brand'] = 'BMW',
		['model'] = 'm3s',
		['price'] = 20000,
		['category'] = 'pdm',
		['hash'] = `m3s`,
		['shop'] = 'pdm',
	},
	['EP3'] = {-- PDM
		['name'] = 'Honda Civic EP3',
		['brand'] = 'Honda',
		['model'] = 'EP3',
		['price'] = 20000,
		['category'] = 'pdm',
		['hash'] = `EP3`,
		['shop'] = 'pdm',
	},
	['sovrs'] = {-- PDM
	    ['name'] = 'Skoda Octavia VRS',
	    ['brand'] = 'Skoda',
	    ['model'] = 'sovrs',
	    ['price'] = 25000,
	    ['category'] = 'pdm',
	    ['hash'] = `sovrs`,
	    ['shop'] = 'pdm',
    },
	['GCMX32016'] = {-- PDM
		['name'] = 'BMW X3 2016',
		['brand'] = 'BMW',
		['model'] = 'GCMX32016',
		['price'] = 25000,
		['category'] = 'pdm',
		['hash'] = `GCMX32016`,
		['shop'] = 'pdm',
	},
	['Q7'] = {-- PDM
		['name'] = 'Audi Q7',
		['brand'] = 'Audi',
		['model'] = 'Q7',
		['price'] = 30000,
		['category'] = 'pdm',
		['hash'] = `Q7`,
		['shop'] = 'pdm',
	},  
	['corsa'] = {-- PDM
		['name'] = 'Vauxhall Corsa',
		['brand'] = 'Vauxhall',
		['model'] = 'corsa',
		['price'] = 30000,
		['category'] = 'pdm',
		['hash'] = `corsa`,
		['shop'] = 'pdm',
	},
	['S3SEDAN'] = {-- PDM
		['name'] = 'Audi A3 2015',
		['brand'] = 'Audi',
		['model'] = 'S3SEDAN',
		['price'] = 30000,
		['category'] = 'pdm',
		['hash'] = `S3SEDAN`,
		['shop'] = 'pdm',
	},
	['gcmgolf8gti'] = {-- PDM
		['name'] = 'Volkswagen Golf GTI 2021',
		['brand'] = 'Volkswagen',
		['model'] = 'gcmgolf8gti',
		['price'] = 35000,
		['category'] = 'pdm',
		['hash'] = `gcmgolf8gti`,
		['shop'] = 'pdm',
	},  
	['FOCUSRS'] = {-- PDM
		['name'] = 'Focus RS',
		['brand'] = 'Focus',
		['model'] = 'FOCUSRS',
		['price'] = 40000,
		['category'] = 'pdm',
		['hash'] = `FOCUSRS`,
		['shop'] = 'pdm',
	}, 
	['ECLIPSE'] = {-- PDM
		['name'] = 'Mitsibushi Eclipse',
		['brand'] = 'Mitsibushi',
		['model'] = 'ECLIPSE',
		['price'] = 50000,
		['category'] = 'pdm',
		['hash'] = `ECLIPSE`,
		['shop'] = 'pdm',
	},    
-- 2-2 Motors
-- 2-2 fifty
    ['GCMYARISGR'] = {-- 2-2
        ['name'] = 'Toyota Yaris GR',
        ['brand'] = 'Toyota',
        ['model'] = 'GCMYARISGR',
        ['price'] = 15000,
        ['category'] = 'fifty',
        ['hash'] = `GCMYARISGR`,
        ['shop'] = 'luxury',
    },
	['gcmdefender1997'] = {-- 2-2
		['name'] = 'Land Rover Defender 90',
		['brand'] = 'Land Rover',
		['model'] = 'gcmdefender1997',
		['price'] = 27500,
		['category'] = 'fifty',
		['hash'] = `gcmdefender1997`,
		['shop'] = 'luxury',
	},
    ['nisgtir'] = {-- 2-2
		['name'] = 'Nissan Pulsar',
		['brand'] = 'Nissan',
		['model'] = 'nisgtir',
		['price'] =  30000,
		['category'] = 'fifty',
		['hash'] = `nisgtir`,
		['shop'] = 'luxury',
    },
    ['civic'] = {-- 2-2
		['name'] = 'Civic 99',
		['brand'] = 'Civic',
		['model'] = 'civic',
		['price'] = 30000,
		['category'] = 'fifty',
		['hash'] = `civic`,
		['shop'] = 'luxury',
    },
    ['lx470'] = {-- 2-2
		['name'] = 'Lexus LX470',
		['brand'] = 'Lexus',
		['model'] = 'lx470',
		['price'] = 30000,
		['category'] = 'fifty',
		['hash'] = `lx470`,
		['shop'] = 'luxury',
    },
    ['nis13'] = {-- 2-2
		['name'] = 'Nissan S13',
		['brand'] = 'Nissan',
		['model'] = 'nis13',
		['price'] = 30000,
		['category'] = 'fifty',
		['hash'] = `nis13`,
		['shop'] = 'luxury',
    },
    ['austminrhd'] = {-- 2-2
	    ['name'] = 'Mini Cooper S',
	    ['brand'] = 'Mini',
	    ['model'] = 'austminrhd',
	    ['price'] = 30000,
	    ['category'] = 'fifty',
	    ['hash'] = `austminrhd`,
	    ['shop'] = 'luxury',
    },
	['na6'] = {-- 2-2
		['name'] = 'Mazda MX5',
		['brand'] = 'Mazda',
		['model'] = 'na6',
		['price'] =  35000,
		['category'] = 'fifty',
		['hash'] = `na6`,
		['shop'] = 'luxury',
    },
	['q820'] = {-- 2-2
	    ['name'] = 'Audi Q8 50TDI 2020',
	    ['brand'] = 'Audi',
	    ['model'] = 'q820',
	    ['price'] = 35000,
	    ['category'] = 'fifty',
	    ['hash'] = `q820`,
	    ['shop'] = 'luxury',
    },
	['golfgtd'] = {-- 2-2
		['name'] = 'Volkswagen Golf GTD',
		['brand'] = 'Volkswagen',
		['model'] = 'golfgtd',
		['price'] = 35000,
		['category'] = 'fifty',
		['hash'] = `golfgtd`,
		['shop'] = 'luxury',
	},
	['DEFENDER21'] = {-- 2-2
		['name'] = 'Land Rover Defender',
		['brand'] = 'Land Rover',
		['model'] = 'DEFENDER21',
		['price'] = 40000,
		['category'] = 'fifty',
		['hash'] = `DEFENDER21`,
		['shop'] = 'luxury',
	},
	['rs318'] = {-- 2-2
		['name'] = 'Audi RS3 2018',
		['brand'] = 'Audi',
		['model'] = 'rs318',
		['price'] = 40000,
		['category'] = 'fifty',
		['hash'] = `rs318`,
		['shop'] = 'luxury',
	},
	['sprinter211'] = {-- 2-2
		['name'] = 'Sprinter 211',
		['brand'] = 'Sprinter',
		['model'] = 'sprinter211',
		['price'] =  40000,
		['category'] = 'fifty',
		['hash'] = `sprinter211`,
		['shop'] = 'luxury',
	},
	['gcmrangerover2022'] = {-- 2-2
		['name'] = 'Range Rover Sport',
		['brand'] = 'Range Rover',
		['model'] = 'gcmrangerover2022',
		['price'] = 42500,
		['category'] = 'fifty',
		['hash'] = `gcmrangerover2022`,
		['shop'] = 'luxury',
	},
    ['mesaxl'] = {-- 2-2
	    ['name'] = 'Canis Gator 4x4',
	    ['brand'] = 'Canis',
	    ['model'] = 'mesaxl',
	    ['price'] = 45000,
	    ['category'] = 'fifty',
	    ['hash'] = `mesaxl`,
	    ['shop'] = 'luxury',
    },
	['dc5'] = {-- 2-2
		['name'] = 'Honda Integra Type-R',
		['brand'] = 'Honda',
		['model'] = 'dc5',
		['price'] = 50000,
		['category'] = 'fifty',
		['hash'] = `dc5`,
		['shop'] = 'luxury',
	},
-- 2-2 onehundred
    ['nissanjuker'] = {-- 2-2 
		['name'] = 'Nissan Juke R',
		['brand'] = 'Nissan',
		['model'] = 'nissanjuker',
		['price'] = 70000,
		['category'] = 'onehundred',
		['hash'] = `nissanjuker`,
		['shop'] = 'luxury',
	},
	['rmodmk7'] = {-- 2-2
	   ['name'] = 'Volkswagen Golf MK7 Pandem',
	   ['brand'] = 'Volkswagen',
	   ['model'] = 'rmodmk7',
	   ['price'] = 75000,
	   ['category'] = 'onehundred',
	   ['hash'] = `rmodmk7`,
	   ['shop'] = 'luxury',
    },
	['cupraprzemo'] = {-- 2-2
		['name'] = 'Cupra',
		['brand'] = 'Cupra',
		['model'] = 'cupraprzemo',
		['price'] = 75000,
		['category'] = 'onehundred',
		['hash'] = `cupraprzemo`,
		['shop'] = 'luxury',
	},
	['22m2cs'] = {-- 2-2
	    ['name'] = 'BMW M2',
	    ['brand'] = 'BMW',
	    ['model'] = '22m2cs',
	    ['price'] = 75000,
	    ['category'] = 'onehundred',
	    ['hash'] = `22m2cs`,
	    ['shop'] = 'luxury',
    },
	['c63w205'] = {-- 2-2
	    ['name'] = 'Mercedes-AMG C63 S 2017',
	    ['brand'] = 'Mercedes',
	    ['model'] = 'c63w205',
	    ['price'] = 80000,
	    ['category'] = 'onehundred',
	    ['hash'] = `c63w205`,
	    ['shop'] = 'luxury',
    },
	['golf75r'] = {-- 2-2
		['name'] = 'Volkswagen Golf R MK 7.5',
		['brand'] = 'Volkswagen',
		['model'] = 'golf75r',
		['price'] = 80000,
		['category'] = 'onehundred',
		['hash'] = `golf75r`,
		['shop'] = 'luxury',
	},
    ['Evoz'] = {-- 2-2
       ['name'] = 'Mitsubishi Evo',
       ['brand'] = 'Mitsubishi',
       ['model'] = 'Evoz',
       ['price'] = 80000,
       ['category'] = 'onehundred',
       ['hash'] = `Evoz`,
       ['shop'] = 'luxury',
    },
	['16cc'] = {-- 2-2
		['name'] = 'Volkswagon Aetron',
		['brand'] = 'Volkswagon',
		['model'] = '16cc',
		['price'] = 80000,
		['category'] = 'onehundred',
		['hash'] = `16cc`,
		['shop'] = 'luxury',
	},
    ['m4f82'] = {-- 2-2
	   ['name'] = 'BMW M4 F82 2015',
	   ['brand'] = 'BMW',
	   ['model'] = 'm4f82',
	   ['price'] = 85000,
	   ['category'] = 'onehundred',
	   ['hash'] = `m4f82`,
	   ['shop'] = 'luxury',
    },
    ['q8prior'] = {-- 2-2
	   ['name'] = 'Audi Q8 2020 Prior edition',
	   ['brand'] = 'Audi',
	   ['model'] = 'q8prior',
	   ['price'] = 90000,
	   ['category'] = 'onehundred',
	   ['hash'] = `q8prior`,
	   ['shop'] = 'luxury',
    },    
	['M140i'] = {-- 2-2
		['name'] = 'BMW M140i',
		['brand'] = 'BMW',
		['model'] = 'M140i',
		['price'] = 90000,
		['category'] = 'onehundred',
		['hash'] = `M140i`,
		['shop'] = 'luxury',
	},
    ['22m135imperf'] = {-- 2-2
		['name'] = 'BMW M135i',
		['brand'] = 'BMW',
		['model'] = '22m135imperf',
		['price'] = 95000,
		['category'] = 'onehundred',
		['hash'] = `22m135imperf`,
		['shop'] = 'luxury',
	},
    ['m4g82c'] = {-- 2-2
	   ['name'] = 'BMW M4 G82',
	   ['brand'] = 'BMW',
	   ['model'] = 'm4g82c',
	   ['price'] = 95000,
	   ['category'] = 'onehundred',
	   ['hash'] = `m4g82c`,
	   ['shop'] = 'luxury',
    },    
	['e63estatesal'] = {-- 2-2
	   ['name'] = 'Mercedes E63 Estate',
	   ['brand'] = 'Mercedes',
	   ['model'] = 'e63estatesal',
	   ['price'] = 95000,
	   ['category'] = 'onehundred',
	   ['hash'] = `e63estatesal`,
	   ['shop'] = 'luxury',
    },   
	['trx'] = {-- 2-2
	    ['name'] = 'RAM Rebel TRX',
	    ['brand'] = 'RAM',
	    ['model'] = 'trx',
	    ['price'] =  100000,
	    ['category'] = 'onehundred',
	    ['hash'] = `trx`,
	    ['shop'] = 'luxury',
    },
    ['cookiers6a'] = {-- 2-2
	    ['name'] = 'Audi RS6 2020',
	    ['brand'] = 'Audi',
	    ['model'] = 'cookiers6a',
	    ['price'] = 100000,
	    ['category'] = 'onehundred',
	    ['hash'] = `cookiers6a`,
	    ['shop'] = 'luxury',
    },    
	['mansrr'] = {-- 2-2
		['name'] = 'Mansory Range Rover',
		['brand'] = 'Range Rover',
		['model'] = 'mansrr',
		['price'] = 100000,
		['category'] = 'onehundred',
		['hash'] = `mansrr`,
		['shop'] = 'luxury',
	},
	['A45S20'] = {-- 2-2
		['name'] = 'Mercedes A45 AMG',
		['brand'] = 'Mercedes',
		['model'] = 'A45S20',
		['price'] = 100000,
		['category'] = 'onehundred',
		['hash'] = `A45S20`,
		['shop'] = 'luxury',
	},
	['20X5M'] = {-- 2-2
		['name'] = 'BMW X5M',
		['brand'] = 'BMW',
		['model'] = '20X5M',
		['price'] = 100000,
		['category'] = 'onehundred',
		['hash'] = `20X5M`,
		['shop'] = 'luxury',
	},    
    ['imprez_civ'] = {-- 2-2
		['name'] = 'Subaru Impreza',
		['brand'] = 'Subaru',
		['model'] = 'imprez_civ',
		['price'] =  100000,
		['category'] = 'onehundred',
		['hash'] = `imprez_civ`,
		['shop'] = 'luxury',
    },    
	['m3e30'] = {-- 2-2
		['name'] = 'BMW E30',
		['brand'] = 'BMW',
		['model'] = 'm3e30',
		['price'] = 100000,
		['category'] = 'onehundred',
		['hash'] = `m3e30`,
		['shop'] = 'luxury',
	},    
	['golfr21'] = {-- 2-2
		['name'] = 'MK8 GolfR',
		['brand'] = 'Golf',
		['model'] = 'golfr21',
		['price'] = 100000,
		['category'] = 'onehundred',
		['hash'] = `golfr21`,
		['shop'] = 'luxury',
	},   
-- 2-2 twohundred
	['m3f80'] = {-- 2-2
		['name'] = '2015 BMW M3 (F80)',
		['brand'] = 'BMW',
		['model'] = 'm3f80',
		['price'] = 105000,
		['category'] = 'twohundred',
		['hash'] = `m3f80`,
		['shop'] = 'luxury',
	}, 
    ['brabus500'] = {-- 2-2
	   ['name'] = 'Brabus 500 4x4',
	   ['brand'] = 'Brabus',
	   ['model'] = 'brabus500',
	   ['price'] = 110000,
	   ['category'] = 'twohundred',
	   ['hash'] = `brabus500`,
	   ['shop'] = 'luxury',
    },    
	['na1'] = {-- 2-2
		['name'] = 'Honda NSX-R',
		['brand'] = 'Honda',
		['model'] = 'na1',
		['price'] = 110000,
		['category'] = 'twohundred',
		['hash'] = `na1`,
		['shop'] = 'luxury',
	},
	['22m3sal'] = {-- 2-2
		['name'] = 'BMW M3 Competition',
		['brand'] = 'BMW',
		['model'] = '22m3sal',
		['price'] = 110000,
		['category'] = 'twohundred',
		['hash'] = `22m3sal`,
		['shop'] = 'luxury',
	},
	['ttrsgs'] = {-- 2-2
		['name'] = 'Audi TTRS',
		['brand'] = 'Audi',
		['model'] = 'ttrsgs',
		['price'] =  110000,
		['category'] = 'twohundred',
		['hash'] = `ttrsgs`,
		['shop'] = 'luxury',
    },    
	['RS615'] = {-- 2-2
		['name'] = 'Audi RS6 2015',
		['brand'] = 'Audi',
		['model'] = 'RS615',
		['price'] = 110000,
		['category'] = 'twohundred',
		['hash'] = `RS615`,
		['shop'] = 'luxury',
	},
	['rmodm3e36'] = {-- 2-2
		['name'] = 'BMW Me E36',
		['brand'] = 'BMW',
		['model'] = 'rmodm3e36',
		['price'] = 110000,
		['category'] = 'twohundred',
		['hash'] = `rmodm3e36`,
		['shop'] = 'luxury',
	},
	['2021M5SAL'] = {-- 2-2
		['name'] = 'BMW M5 2021',
		['brand'] = 'BMW',
		['model'] = '2021M5SAL',
		['price'] = 110000,
		['category'] = 'twohundred',
		['hash'] = `2021M5SAL`,
		['shop'] = 'luxury',
	},    
	['cp9a'] = {-- 2-2
		['name'] = 'Evo VI',
		['brand'] = 'Evo',
		['model'] = 'cp9a',
		['price'] = 115000,
		['category'] = 'twohundred',
		['hash'] = `cp9a`,
		['shop'] = 'luxury',
	},    
	['1016URUS'] = {-- 2-2
		['name'] = 'Lamborghini Urus',
		['brand'] = 'Lamborghini',
		['model'] = '1016URUS',
		['price'] = 120000,
		['category'] = 'twohundred',
		['hash'] = `1016URUS`,
		['shop'] = 'luxury',
	},   
	['s500w223'] = {-- 2-2
		['name'] = '2022 Mercedes-Benz S-class W223 AMG Line',
		['brand'] = 'Mercedes-Benz',
		['model'] = 's500w223',
		['price'] = 120000,
		['category'] = 'twohundred',
		['hash'] = `s500w223`,
		['shop'] = 'luxury',
	},
	['fd'] = {-- 2-2
		['name'] = 'Mazda RX-7 Spirit R FD3S',
		['brand'] = 'Mazda',
		['model'] = 'fd',
		['price'] = 120000,
		['category'] = 'twohundred',
		['hash'] = `fd`,
		['shop'] = 'luxury',
	},     
	['rocketg900'] = {-- 2-2
		['name'] = 'Brabus G Wagon',
		['brand'] = 'Brabus',
		['model'] = 'rocketg900',
		['price'] =  120000,
		['category'] = 'twohundred',
		['hash'] = `rocketg900`,
		['shop'] = 'luxury',
	},
	['E63SSAL'] = {-- 2-2
		['name'] = 'Mercedes-Benz E63 2021',
		['brand'] = 'Mercedes-Benz',
		['model'] = 'E63SSAL',
		['price'] = 120000,
		['category'] = 'twohundred',
		['hash'] = `E63SSAL`,
		['shop'] = 'luxury',
	},    
	['mflyingspur'] = {-- 2-2
		['name'] = 'Bentley Flying Spur',
		['brand'] = 'Bentley',
		['model'] = 'mflyingspur',
		['price'] = 125000,
		['category'] = 'twohundred',
		['hash'] = `mflyingspur`,
		['shop'] = 'luxury',
	},
	['bmwm5touring'] = {-- 2-2
		['name'] = 'BMW M5 Touring',
		['brand'] = 'BMW',
		['model'] = 'bmwm5touring',
		['price'] = 125000,
		['category'] = 'twohundred',
		['hash'] = `bmwm5touring`,
		['shop'] = 'luxury',
	},    
    ['pandemraptor'] = {-- 2-2
	   ['name'] = 'Ford Pandem Raptor',
	   ['brand'] = 'Ford',
	   ['model'] = 'pandemraptor',
	   ['price'] = 150000,
	   ['category'] = 'twohundred',
	   ['hash'] = `pandemraptor`,
	   ['shop'] = 'luxury',
    },
    ['svr14'] = {-- 2-2
		['name'] = 'Range Rover SVR',
		['brand'] = 'Range Rover',
		['model'] = 'svr14',
		['price'] =  170000,
		['category'] = 'twohundred',
		['hash'] = `svr14`,
		['shop'] = 'luxury',
    },
	['AMGGT'] = {-- 2-2
		['name'] = 'Mercedes AMG GT',
		['brand'] = 'Mercedes',
		['model'] = 'AMGGT',
		['price'] = 175000,
		['category'] = 'twohundred',
		['hash'] = `AMGGT`,
		['shop'] = 'luxury',
	},    
	['lumma'] = {-- 2-2
		['name'] = 'Mercedes G Wagon',
		['brand'] = 'Mercedes',
		['model'] = 'lumma',
		['price'] = 180000,
		['category'] = 'twohundred',
		['hash'] = `lumma`,
		['shop'] = 'luxury',
    },
	['2022jeep'] = {-- 2-2
		['name'] = '2022 Jeep',
		['brand'] = 'Jeep',
		['model'] = '2022jeep',
		['price'] =  185000,
		['category'] = 'twohundred',
		['hash'] = `2022jeep`,
		['shop'] = 'luxury',
	},
	['rs6c8'] = {-- 2-2
       ['name'] = 'Audi RS6 Sedan 2021',
       ['brand'] = 'Audi',
       ['model'] = 'rs6c8',
       ['price'] = 185000,
       ['category'] = 'twohundred',
       ['hash'] = `rs6c8`,
       ['shop'] = 'luxury',
    },
	['760m'] = {-- 2-2
		['name'] = 'BMW 760 Manhart',
		['brand'] = 'BMW',
		['model'] = '760m',
		['price'] = 195000,
		['category'] = 'twohundred',
		['hash'] = `760m`,
		['shop'] = 'luxury',
	},  
    ['brabus900bs'] = {-- 2-2
       ['name'] = 'Brabus Rocket 900',
       ['brand'] = 'Brabus',
       ['model'] = 'brabus900bs',
       ['price'] = 195000,
       ['category'] = 'twohundred',
       ['hash'] = `brabus900bs`,
       ['shop'] = 'luxury',
    },
    ['18performante'] = {-- 2-2
       ['name'] = '2018 Lamborghini Huracan Performante',
       ['brand'] = 'Lamborghini',
       ['model'] = '18performante',
       ['price'] = 195000,
       ['category'] = 'twohundred',
       ['hash'] = `18performante`,
       ['shop'] = 'luxury',
    },    
	['2021rs7sal'] = {-- 2-2
		['name'] = '2021 RS7',
		['brand'] = 'Audi',
		['model'] = '2021rs7sal',
		['price'] =  195000,
		['category'] = 'twohundred',
		['hash'] = `2021rs7sal`,
		['shop'] = 'luxury',
	},
    ['a80'] = {-- 2-2
		['name'] = 'Toyota Supra',
		['brand'] = 'Toyota',
		['model'] = 'a80',
		['price'] =  200000,
		['category'] = 'twohundred',
		['hash'] = `a80`,
		['shop'] = 'luxury',
    },
	['dawnonyx'] = {-- 2-2
		['name'] = 'Rolls Royce Dawn',
		['brand'] = 'Rolls Royce',
		['model'] = 'dawnonyx',
		['price'] = 200000,
		['category'] = 'twohundred',
		['hash'] = `dawnonyx`,
		['shop'] = 'luxury',
	},
-- 2-2 threehundred
	['pgt3rs19'] = {-- 2-2
		['name'] = 'Porsche GT3 RS',
		['brand'] = 'Porsche',
		['model'] = 'pgt3rs19',
		['price'] = 205000,
		['category'] = 'threehundred',
		['hash'] = `pgt3rs19`,
		['shop'] = 'luxury',
	},    
    ['lbperfs'] = {-- 2-2
       ['name'] = 'Lambroghini Hurracan Performante Spyder LB',
       ['brand'] = 'Lambroghini',
       ['model'] = 'lbperfs',
       ['price'] = 205000,
       ['category'] = 'threehundred',
       ['hash'] = `lbperfs`,
       ['shop'] = 'luxury',
    },    
	['gtr'] = {-- 2-2
		['name'] = 'Nissan GTR R35',
		['brand'] = 'Nissan',
		['model'] = 'gtr',
		['price'] = 210000,
		['category'] = 'threehundred',
		['hash'] = `gtr`,
		['shop'] = 'luxury',
	},
	['skyline'] = {-- 2-2
		['name'] = 'Nissan Skyline GTR R-34',
		['brand'] = 'Nissan',
		['model'] = 'skyline',
		['price'] = 210000,
		['category'] = 'threehundred',
		['hash'] = `skyline`,
		['shop'] = 'luxury',
	},    
	['gtrnismo17'] = {-- 2-2
		['name'] = 'Nissan GTR R35 Nismo',
		['brand'] = 'Nissan',
		['model'] = 'gtrnismo17',
		['price'] = 215000,
		['category'] = 'threehundred',
		['hash'] = `gtrnismo17`,
		['shop'] = 'luxury',
	},      
	['lp700'] = {-- 2-2
		['name'] = 'Lamborghini Aventador',
		['brand'] = 'Lamborghini',
		['model'] = 'lp700',
		['price'] =  215000,
		['category'] = 'threehundred',
		['hash'] = `lp700`,
		['shop'] = 'luxury',
	},    
	['992gt3'] = {-- 2-2
		['name'] = 'Porsche GT3 922',
		['brand'] = 'Porsche',
		['model'] = '992gt3',
		['price'] = 215000,
		['category'] = 'threehundred',
		['hash'] = `992gt3`,
		['shop'] = 'luxury',
	},
	['audirsq8'] = {-- 2-2
		['name'] = 'Audi RSQ8',
		['brand'] = 'Audi',
		['model'] = 'audirsq8',
		['price'] = 215000,
		['category'] = 'threehundred',
		['hash'] = `audirsq8`,
		['shop'] = 'luxury',
	},
	['brabusghost700'] = {-- 2-2
	    ['name'] = 'Brabus Ghost',
	    ['brand'] = 'Brabus',
	    ['model'] = 'brabusghost700',
	    ['price'] = 235000,
	    ['category'] = 'threehundred',
	    ['hash'] = `brabusghost700`,
	    ['shop'] = 'luxury',
    },  
	['manhr8przemo'] = {-- 2-2
		['name'] = 'Audi R8 Manhart',
		['brand'] = 'Audi',
		['model'] = 'manhr8przemo',
		['price'] = 250000,
		['category'] = 'threehundred',
		['hash'] = `manhr8przemo`,
		['shop'] = 'luxury',
	},   
    ['aventsvjr'] = {-- 2-2
       ['name'] = 'Lamborghini Aventador SVJ',
       ['brand'] = 'Lamborghini',
       ['model'] = 'aventsvjr',
       ['price'] =  250000,
       ['category'] = 'threehundred',
       ['hash'] = `aventsvjr`,
       ['shop'] = 'luxury',
    },     
	['720stc'] = {-- 2-2
		['name'] = 'Mclaren 720s Topcar Fury',
		['brand'] = 'Mclaren',
		['model'] = '720stc',
		['price'] = 265000,
		['category'] = 'threehundred',
		['hash'] = `720stc`,
		['shop'] = 'luxury',
	},   
	['oycval'] = {-- 2-2
		['name'] = 'Aston Martin Valhalla',
		['brand'] = 'Aston Martin',
		['model'] = 'oycval',
		['price'] = 275000,
		['category'] = 'threehundred',
		['hash'] = `oycval`,
		['shop'] = 'luxury',
	}, 
-- 2-2 fourhundredplus
	['teslapd'] = {-- 2-2
		['name'] = 'Tesla Model S Prior Design',
		['brand'] = 'Tesla',
		['model'] = 'teslapd',
		['price'] = 485000,
		['category'] = 'fourhundredplus',
		['hash'] = `teslapd`,
		['shop'] = 'luxury',
	},    
	['bc'] = {-- 2-2
		['name'] = 'Pagani Huayra BC',
		['brand'] = 'Pagani',
		['model'] = 'bc',
		['price'] = 485000,
		['category'] = 'fourhundredplus',
		['hash'] = `bc`,
		['shop'] = 'luxury',
	},    
	['mcf1'] = {-- 2-2
		['name'] = 'McLaren F1 1993',
		['brand'] = 'McLaren',
		['model'] = 'mcf1',
		['price'] = 499999,
		['category'] = 'fourhundredplus',
		['hash'] = `mcf1`,
		['shop'] = 'luxury',
	},    
	['p1'] = {-- 2-2
		['name'] = 'McLaren P1',
		['brand'] = 'McLaren',
		['model'] = 'p1',
		['price'] = 525000,
		['category'] = 'fourhundredplus',
		['hash'] = `p1`,
		['shop'] = 'luxury',
	},    
	['918'] = {-- 2-2
		['name'] = 'Porsche 918',
		['brand'] = 'Porsche',
		['model'] = '918',
		['price'] = 550000,
		['category'] = 'fourhundredplus',
		['hash'] = `918`,
		['shop'] = 'luxury',
	},    
	['imola'] = {-- 2-2
		['name'] = 'Pagani Imola',
		['brand'] = 'Pagani',
		['model'] = 'imola',
		['price'] = 550000,
		['category'] = 'fourhundredplus',
		['hash'] = `imola`,
		['shop'] = 'luxury',
    },    
	['agera2011'] = {-- 2-2
		['name'] = 'Koenigsegg Agera 2011',
		['brand'] = 'Koenigsegg',
		['model'] = 'agera2011',
		['price'] = 565000,
		['category'] = 'fourhundredplus',
		['hash'] = `agera2011`,
		['shop'] = 'luxury',
    },    
	['roadster'] = {-- 2-2
		['name'] = 'Tesla Roadster',
		['brand'] = 'Tesla',
		['model'] = 'roadster',
		['price'] = 565000,
		['category'] = 'fourhundredplus',
		['hash'] = `roadster`,
		['shop'] = 'luxury',
	},
    ['regera16'] = {-- 2-2
		['name'] = 'Koenigsegg Regera',
		['brand'] = 'Koenigsegg',
		['model'] = 'regera16',
		['price'] = 575000,
		['category'] = 'fourhundredplus',
		['hash'] = `regera16`,
		['shop'] = 'luxury',
    },
	['GEMERA'] = {-- 2-2
		['name'] = 'Koenigsegg Gemera',
		['brand'] = 'Koenigsegg',
		['model'] = 'GEMERA',
		['price'] = 575000,
		['category'] = 'fourhundredplus',
		['hash'] = `GEMERA`,
		['shop'] = 'luxury',
	},
	['venenor'] = {-- 2-2
		['name'] = 'Lamborghini Veneno ',
		['brand'] = 'Lamborghini',
		['model'] = 'venenor',
		['price'] = 575000,
		['category'] = 'fourhundredplus',
		['hash'] = `venenor`,
		['shop'] = 'luxury',
	},
	['ie'] = {-- 2-2
		['name'] = 'Apollo IE',
		['brand'] = 'Apollo',
		['model'] = 'ie',
		['price'] = 585000,
		['category'] = 'fourhundredplus',
		['hash'] = `ie`,
		['shop'] = 'luxury',
	},    
-- 2-2 Miscellaneous
-- 2-2 Trucks/Lorry
    ['man'] = {-- 2-2 Trucks/Lorry
        ['name'] = 'MAN TGX V8 Euro 5',
        ['brand'] = 'MAN',
        ['model'] = 'man',
        ['price'] = 50000,
        ['category'] = 'miscellaneous',
        ['hash'] = `man`,
        ['shop'] = 'luxury',
    }, 
    ['mulef'] = {-- 2-2 Trucks/Lorry
        ['name'] = 'Mule Flatbed',
        ['brand'] = 'Mule',
        ['model'] = 'mulef',
        ['price'] = 40000,
        ['category'] = 'miscellaneous',
        ['hash'] = `mulef`,
        ['shop'] = 'luxury',
    },
    ['phantom'] = {-- 2-2 Trucks/Lorry
        ['name'] = 'Phantom Truck',
        ['brand'] = 'Phantom',
        ['model'] = 'phantom',
        ['price'] = 50000,
        ['category'] = 'miscellaneous',
        ['hash'] = `phantom`,
        ['shop'] = 'luxury',
    },
-- 2-2 Bikes
	['cfmotoz10'] = {-- 2-2 Bikes
		['name'] = 'CF Moto Buggy',
		['brand'] = 'CF Moto',
		['model'] = 'cfmotoz10',
		['price'] =  24000,
		['category'] = 'miscellaneous',
		['hash'] = `cfmotoz10`,
		['shop'] = 'luxury',
	},
	['gokart'] = {-- 2-2
		['name'] = 'Go-kart',
		['brand'] = 'Go-kart',
		['model'] = 'gokart',
		['price'] = 275000,
		['category'] = 'miscellaneous',
		['hash'] = `gokart`,
		['shop'] = 'luxury',
	},
	['h2'] = {-- 2-2 Bike
		['name'] = 'Kawasaki Ninja H2',
		['brand'] = 'Kawasaki',
		['model'] = 'h2',
		['price'] =  75000,
		['category'] = 'miscellaneous',
		['hash'] = `h2`,
		['shop'] = 'luxury',
	},
	['hdiron883'] = {-- 2-2 Bike
		['name'] = 'Harley Davidson Sportstar Iron',
		['brand'] = 'Harley Davidson',
		['model'] = 'hdiron883',
		['price'] =  25000,
		['category'] = 'miscellaneous',
		['hash'] = `hdiron883`,
		['shop'] = 'luxury',
	},
	['born'] = {-- 2-2 Bike
	    ['name'] = 'Harley Davidson Bike',
	    ['brand'] = 'Harley Davidson',
	    ['model'] = 'born',
	    ['price'] =  25000,
	    ['category'] = 'miscellaneous',
	    ['hash'] = `born`,
	    ['shop'] = 'luxury',
    },
	['y1700max'] = {-- 2-2 Bike
		['name'] = 'Yamaha 1700 Max',
		['brand'] = 'Yamaha',
		['model'] = 'y1700max',
		['price'] =  28000,
		['category'] = 'miscellaneous',
		['hash'] = `y1700max`,
		['shop'] = 'luxury',
	},
	['vespa'] = {-- 2-2 Bike
		['name'] = 'Vespa',
		['brand'] = 'Vespa',
		['model'] = 'vespa',
		['price'] =  10000,
		['category'] = 'miscellaneous',
		['hash'] = `vespa`,
		['shop'] = 'luxury',
	},
	['mt09'] = {-- 2-2 Bike
		['name'] = 'Yamaha Street Bike',
		['brand'] = 'Yamaha',
		['model'] = 'mt09',
		['price'] =  28000,
		['category'] = 'miscellaneous',
		['hash'] = `mt09`,
		['shop'] = 'luxury',
	},
	['22surron'] = {-- 2-2 Bike
		['name'] = 'Surron Bike',
		['brand'] = 'Surron',
		['model'] = '22surron',
		['price'] = 7500,
		['category'] = 'miscellaneous',
		['hash'] = `22surron`,
		['shop'] = 'luxury',
	},
	['tmaxdx'] = {-- 2-2 Bike
		['name'] = 'T Max',
		['brand'] = 'T Max',
		['model'] = 'tmaxdx',
		['price'] = 7500,
		['category'] = 'miscellaneous',
		['hash'] = `tmaxdx`,
		['shop'] = 'luxury',
	},
	['bmws'] = {-- 2-2 Bike
		['name'] = 'BMW S1000RR',
		['brand'] = 'BMW',
		['model'] = 'bmws',
		['price'] = 45000,
		['category'] = 'miscellaneous',
		['hash'] = `bmws`,
		['shop'] = 'luxury',
	},
	['r1'] = {-- 2-2 Bike
		['name'] = 'Yamaha R1',
		['brand'] = 'Yamaha',
		['model'] = 'r1',
		['price'] = 40000,
		['category'] = 'miscellaneous',
		['hash'] = `r1`,
		['shop'] = 'luxury',
	},
    ['2020exc'] = {-- 2-2 Bike
        ['name'] = 'KTM 250',
        ['brand'] = 'KTM',
        ['model'] = '2020exc',
        ['price'] =  15000,
        ['category'] = 'miscellaneous',
        ['hash'] = `2020exc`,
        ['shop'] = 'luxury',
    },
-- 2-2 Job Vehicles
	['vivio'] = {-- 2-2 Chings Chopsticks
	    ['name'] = 'Chings Chopsticks Vivio',
	    ['brand'] = 'Chings Chopsticks',
	    ['model'] = 'vivio',
	    ['price'] =  2000,
	    ['category'] = 'miscellaneous',
	    ['hash'] = `vivio`,
	    ['shop'] = 'luxury',
    },
	['mtanker2'] = {-- 2-2 MUC
	    ['name'] = 'MUC Oil Tanker',
	    ['brand'] = 'MUC',
	    ['model'] = 'mtanker2',
	    ['price'] =  2000,
	    ['category'] = 'miscellaneous',
	    ['hash'] = `mtanker2`,
	    ['shop'] = 'luxury',
    },
    ['uspstrans'] = {-- 2-2 MUC
	    ['name'] = 'MUC Ford Transit',
	    ['brand'] = 'MUC',
	    ['model'] = 'uspstrans',
	    ['price'] =  2000,
	    ['category'] = 'miscellaneous',
	    ['hash'] = `uspstrans`,
	    ['shop'] = 'luxury',
    },
	['rs323'] = {-- 2-2 Job Vehicle
		['name'] = '2-2 Audi RS3 2-2',
		['brand'] = 'Audi',
		['model'] = 'rs323',
		['price'] = 2000,
		['category'] = 'miscellaneous',
		['hash'] = `rs323`,
		['shop'] = 'luxury',
	},
	['gcmix2021'] = {-- 2-2 Job Vehicle
		['name'] = '2-2 BMW IX 2021',
		['brand'] = 'BMW',
		['model'] = 'gcmix2021',
		['price'] = 2000,
		['category'] = 'miscellaneous',
		['hash'] = `gcmix2021`,
		['shop'] = 'luxury',
	},
	['s650limo'] = {-- 2-2 Limo
		['name'] = 'Mayors Limousine',
		['brand'] = 'Limo',
		['model'] = 's650limo',
		['price'] = 2000,
		['category'] = 'miscellaneous',
		['hash'] = `s650limo`,
		['shop'] = 'luxury',
	},	
--2-2 Limited
-- 5of5
	['gt2rwb'] = {-- 5of5
		['name'] = '5 of 5 Porsche GT2 1992 RWB',
		['brand'] = 'Porsche',
		['model'] = 'gt2rwb',
		['price'] =  400000,
		['category'] = 'limited',
		['hash'] = `gt2rwb`,
		['shop'] = 'luxury',
    },
	['topfoil'] = {-- 5of5
		['name'] = '5 of 5 Topfoil Evo',
		['brand'] = 'Evo',
		['model'] = 'topfoil',
		['price'] =  350000,
		['category'] = 'limited',
		['hash'] = `topfoil`,
		['shop'] = 'luxury',
	},
-- 3of3
	['topcarrsq8'] = {-- 3of3
		['name'] = '3 OF 3 Audi RSQ8 Topcar',
		['brand'] = 'Audi',
		['model'] = 'topcarrsq8',
		['price'] = 480000,
		['category'] = 'limited',
		['hash'] = `topcarrsq8`,
		['shop'] = 'luxury',
    },
	['coastline'] = {-- 3of3
		['name'] = '3 OF 3 Rolls-Royce Cullinan Mansory Coastline ',
		['brand'] = 'Rolls-Royce',
		['model'] = 'coastline',
		['price'] =  450000,
		['category'] = 'limited',
		['hash'] = `coastline`,
		['shop'] = 'luxury',
	},
-- 2of2
	['btsupra94'] = {-- 2of2
	    ['name'] = '2 of 2 Fast & Furious Supra',
	    ['brand'] = 'Fast & Furious',
	    ['model'] = 'btsupra94',
	    ['price'] =  650000,
	    ['category'] = 'limited',
	    ['hash'] = `btsupra94`,
	    ['shop'] = 'luxury',
    },
    ['fnflan'] = {-- 2of2
	    ['name'] = '2 of 2 Fast & Furious Evo IX',
	    ['brand'] = 'Fast & Furious',
	    ['model'] = 'fnflan',
	    ['price'] =  650000,
	    ['category'] = 'limited',
	    ['hash'] = `fnflan`,
	    ['shop'] = 'luxury',
    },
    ['fnf4r34'] = {-- 2 of 2
	   ['name'] = '2 of 2 Fast and Furious GTR',
	   ['brand'] = 'Fast and Furious',
	   ['model'] = 'fnf4r34',
	   ['price'] = 650000,
	   ['category'] = 'limited',
	   ['hash'] = `fnf4r34`,
	   ['shop'] = 'luxury',
    },
-- Donation Shop
	['gcmcliors2000'] = {-- Donation Shop
		['name'] = 'Renault Clio',
		['brand'] = 'Renault',
		['model'] = 'gcmcliors2000',
		['price'] = 10,
		['category'] = 'donation',
		['hash'] = `gcmcliors2000`,
		['shop'] = 'donation',
	},
	['broncobadlands'] = {-- Donation Shop
		['name'] = 'Ford Bronco',
		['brand'] = 'Ford',
		['model'] = 'broncobadlands',
		['price'] = 10,
		['category'] = 'donation',
		['hash'] = `broncobadlands`,
		['shop'] = 'donation',
	},
	['xp210'] = {-- Donation Shop 
		['name'] = 'Totoya GR',
		['brand'] = 'Totoya',
		['model'] = 'xp210',
		['price'] = 10,
		['category'] = 'donation',
		['hash'] = `xp210`,
		['shop'] = 'donation',
    },
	['rrsport'] = {-- Donation Shop
		['name'] = 'Range Rover Sport',
		['brand'] = 'Range Rover',
		['model'] = 'rrsport',
		['price'] = 20,
		['category'] = 'donation',
		['hash'] = `rrsport`,
		['shop'] = 'donation',
	},	
	['19x7m'] = {-- Donation Shop
		['name'] = 'BMW X7M',
		['brand'] = 'BMW',
		['model'] = '19x7m',
		['price'] = 30,
		['category'] = 'donation',
		['hash'] = `19x7m`,
		['shop'] = 'donation',
	},
	['hs2000'] = {-- Donation Shop
		['name'] = 'Honda S2000',
		['brand'] = 'Honda',
		['model'] = 'hs2000',
		['price'] = 30,
		['category'] = 'donation',
		['hash'] = `hs2000`,
		['shop'] = 'donation',
	},
	['is300'] = {-- Donation Shop
		['name'] = 'Lexus IS300',
		['brand'] = 'Lexus',
		['model'] = 'is300',
		['price'] = 30,
		['category'] = 'donation',
		['hash'] = `is300`,
		['shop'] = 'donation',
	},	
	['n350z'] = {-- Donation Shop
		['name'] = 'Nissan 350Z',
		['brand'] = 'Nissan',
		['model'] = 'n350z',
		['price'] = 30,
		['category'] = 'donation',
		['hash'] = `n350z`,
		['shop'] = 'donation',
	},
	['daf'] = {-- Donation Shop
		['name'] = 'DAF XF',
		['brand'] = 'DAF',
		['model'] = 'daf',
		['price'] = 40,
		['category'] = 'donation',
		['hash'] = `daf`,
		['shop'] = 'donation',
	},	
	['r33'] = {-- Donation Shop
		['name'] = 'Nissan Skyline GTR R33 V-Spec',
		['brand'] = 'Nissan',
		['model'] = 'r33',
		['price'] = 40,
		['category'] = 'donation',
		['hash'] = `r33`,
		['shop'] = 'donation',
	},
	['jimny'] = {-- Donation Shop
		['name'] = 'Suzski Jimny',
		['brand'] = 'Suzski',
		['model'] = 'jimny',
		['price'] = 40,
		['category'] = 'donation',
		['hash'] = `jimny`,
		['shop'] = 'donation',
	},
	['er34'] = {-- Donation Shop
		['name'] = 'Nissan ER34',
		['brand'] = 'Nissan',
		['model'] = 'er34',
		['price'] = 40,
		['category'] = 'donation',
		['hash'] = `er34`,
		['shop'] = 'donation',
    },
	['gr86'] = {-- Donation Shop
		['name'] = 'Toyota GR86',
		['brand'] = 'Toyota',
		['model'] = 'gr86',
		['price'] =  40,
		['category'] = 'donation',
		['hash'] = `gr86`,
		['shop'] = 'donation',
    },	
	['bnr32'] = {-- Donation Shop
		['name'] = 'Nissan R32 GTR',
		['brand'] = 'Nissan',
		['model'] = 'bnr32',
		['price'] = 40,
		['category'] = 'donation',
		['hash'] = `bnr32`,
		['shop'] = 'donation',
	},
	['m3tou'] = {-- Donation Shop 
		['name'] = 'BMW M3 G81 Touring',
		['brand'] = 'BMW',
		['model'] = 'm3tou',
		['price'] = 50,
		['category'] = 'donation',
		['hash'] = `m3tou`,
		['shop'] = 'donation',
	},								
	['rcf'] = {-- Donation Shop
		['name'] = 'Lexus RCF',
		['brand'] = 'Lexus',
		['model'] = 'rcf',
		['price'] = 50,
		['category'] = 'donation',
		['hash'] = `rcf`,
		['shop'] = 'donation',
	},		
	['c63wagon'] = {-- Donation Shop
		['name'] = 'Mercedes C63 Wagon',
		['brand'] = 'Golf',
		['model'] = 'golfr21',
		['price'] = 50,
		['category'] = 'donation',
		['hash'] = `c63wagon`,
		['shop'] = 'donation',
	},
	['razerx3'] = {-- Donation Shop 
		['name'] = 'Can AM',
		['brand'] = 'Can AM',
		['model'] = 'razerx3',
		['price'] = 50,
		['category'] = 'donation',
		['hash'] = `razerx3`,
		['shop'] = 'donation',
	},
	['audirs3sedan22'] = {-- Donation Shop
		['name'] = 'Audi RS3 2022',
		['brand'] = 'Audi',
		['model'] = 'audirs3sedan22',
		['price'] = 50,
		['category'] = 'donation',
		['hash'] = `audirs3sedan22`,
		['shop'] = 'donation',
	},
	['mbc63'] = {-- Donation Shop 
		['name'] = 'Mercedes C63',
		['brand'] = 'Mercedes',
		['model'] = 'mbc63',
		['price'] = 50,
		['category'] = 'donation',
		['hash'] = `mbc63`,
		['shop'] = 'donation',
	},
	['rmodmustang'] = {-- Donation Shop
	    ['name'] = 'Ford Mustang GT',
	    ['brand'] = 'Ford',
	    ['model'] = 'rmodmustang',
	    ['price'] =  60,
	    ['category'] = 'donation',
	    ['hash'] = `rmodmustang`,
	    ['shop'] = 'donation',
    },
	['shelbygt500'] = {-- Donation Shop 
		['name'] = 'Ford Shelby GT500',
		['brand'] = 'Ford',
		['model'] = 'shelbygt500',
		['price'] = 60,
		['category'] = 'donation',
		['hash'] = `shelbygt500`,
		['shop'] = 'donation',
    },
	['modelx'] = {-- Donation Shop
		['name'] = 'Tesla Model X',
		['brand'] = 'Tesla',
		['model'] = 'modelx',
		['price'] = 60,
		['category'] = 'donation',
		['hash'] = `modelx`,
		['shop'] = 'donation',
	},
	['gtz34'] = {-- Donation Shop 
	    ['name'] = 'Zlaywork GTR',
	    ['brand'] = 'Zlaywork',
	    ['model'] = 'gtz34',
	    ['price'] = 70,
	    ['category'] = 'donation',
	    ['hash'] = `gtz34`,
	    ['shop'] = 'donation',
    },	
	['300zw'] = {-- Donation Shop 
		['name'] = 'Zlayworks Nissan Fairlady Z',
		['brand'] = 'Zlaywork',
		['model'] = '300zw',
		['price'] = 70,
		['category'] = 'donation',
		['hash'] = `300zw`,
		['shop'] = 'donation',
	},
	['jzx100'] = {-- Donation Shop
		['name'] = 'Toyota Chaser JZX100',
		['brand'] = 'Toyota',
		['model'] = 'jzx100',
		['price'] = 100,
		['category'] = 'donation',
		['hash'] = `jzx100`,
		['shop'] = 'donation',
	},	
	['180sx'] = {-- Donation Shop
		['name'] = 'Nissan 180SX',
		['brand'] = 'Nissan',
		['model'] = '180sx',
		['price'] = 100,
		['category'] = 'donation',
		['hash'] = `180sx`,
		['shop'] = 'donation',
	},
	['hatestang'] = {-- Donation Shop
		['name'] = 'Ford Mustang Drift',
		['brand'] = 'Ford',
		['model'] = 'hatestang',
		['price'] =  100,
		['category'] = 'donation',
		['hash'] = `hatestang`,
		['shop'] = 'donation',
    },
	['razerformulad'] = {-- Donation Shop
		['name'] = 'Formula Drift S13',
		['brand'] = 'Formula',
		['model'] = 'razerformulad',
		['price'] = 100,
		['category'] = 'donation',
		['hash'] = `razerformulad`,
		['shop'] = 'donation',
    },	
	['rmodf12tdf'] = {-- Donation Shop 
		['name'] = 'Ferrari F12',
		['brand'] = 'Ferrari',
		['model'] = 'rmodf12tdf',
		['price'] = 100,
		['category'] = 'donation',
		['hash'] = `rmodf12tdf`,
		['shop'] = 'donation',
	},	
	['fm488'] = {-- Donation Shop
		['name'] = 'Ferrari 488 Mansory',
		['brand'] = 'Ferrari',
		['model'] = 'fm488',
		['price'] = 100,
		['category'] = 'donation',
		['hash'] = `fm488`,
		['shop'] = 'donation',
	},		
	['lp670'] = {-- Donation Shop
		['name'] = 'Lamborghini Murcilago',
		['brand'] = 'Lamborghini',
		['model'] = 'lp670',
		['price'] = 100,
		['category'] = 'donation',
		['hash'] = `lp670`,
		['shop'] = 'donation',
	},
	['lfa'] = {-- Donation Shop
	    ['name'] = 'Lecus LFA',
	    ['brand'] = 'Brabus',
	    ['model'] = 'lfa',
	    ['price'] = 120,
	    ['category'] = 'donation',
	    ['hash'] = `lfa`,
	    ['shop'] = 'donation',
    },	
	['ocnetrongt'] = {-- Donation Shop
		['name'] = 'Audi E-Tron',
		['brand'] = 'Audi',
		['model'] = 'ocnetrongt',
		['price'] = 120,
		['category'] = 'donation',
		['hash'] = `ocnetrongt`,
		['shop'] = 'donation',
	},
	['gcm765ltspider'] = {-- Donation Shop
		['name'] = 'Mclaren 765lt Spyder',
		['brand'] = 'Mclaren',
		['model'] = 'gcm765ltspider',
		['price'] = 120,
		['category'] = 'donation',
		['hash'] = `gcm765ltspider`,
		['shop'] = 'donation',
	},
	['sianr'] = {-- Donation Shop
		['name'] = 'Sian Roadster',
		['brand'] = 'Sian',
		['model'] = 'sianr',
		['price'] =  120,
		['category'] = 'donation',
		['hash'] = `sianr`,
		['shop'] = 'donation',
    },
-- Boats
    ['seashark'] = {-- Boats
		['name'] = 'Boat',
		['brand'] = 'Jetski',
		['model'] = 'seashark',
		['price'] = 10000,
		['category'] = 'boats',
		['hash'] = `-1030275036`,
		['shop'] = 'boat',
    },
    ['dinghy'] = {-- Boats
		['name'] = 'Boat',
		['brand'] = 'Dinghy',
		['model'] = 'dinghy',
		['price'] = 30000,
		['category'] = 'boats',
		['hash'] = `1033245328`,
		['shop'] = 'boat',
    },
    ['speeder'] = {-- Boats
		['name'] = 'Boat',
		['brand'] = 'Speeder',
		['model'] = 'speeder',
		['price'] = 50000,
		['category'] = 'boats',
		['hash'] = `231083307`,
		['shop'] = 'boat',
    },
    ['suntrap'] = {-- Boats
		['name'] = 'Boat',
		['brand'] = 'Suntrap',
		['model'] = 'suntrap',
		['price'] = 100000,
		['category'] = 'boats',
		['hash'] = `-282946103`,
		['shop'] = 'boat',
    },
-- Helicopters
    ['buzzard2'] = {-- Helicopters                          
		['name'] = 'Buzzard',
		['brand'] = 'Helicopter',
		['model'] = 'buzzard2',
		['price'] = 10000000,
		['category'] = 'helicopter',
		['hash'] = `0x2C75F0DD`,
		['shop'] = 'air',
    },    
    ['frogger'] = {-- Helicopters                            
		['name'] = 'Frogger',
		['brand'] = 'Helicopter',
		['model'] = 'frogger',
		['price'] = 13000000,
		['category'] = 'helicopter',
		['hash'] = `0x2C634FBD`,
		['shop'] = 'air',
    },
-- Planes
    ['velum'] = {-- Planes                           
		['name'] = 'Velum',
		['brand'] = 'Plane',
		['model'] = 'velum',
		['price'] = 15000000,
		['category'] = 'planes',
		['hash'] = `0x9C429B6A`,
		['shop'] = 'air',
    },
    ['luxor'] = {-- Planes                            
		['name'] = 'Luxor',
		['brand'] = 'Plane',
		['model'] = 'luxor',
		['price'] = 15000000,
		['category'] = 'planes',
		['hash'] = `0x250B0C5E`,
		['shop'] = 'air',
    },
    ['mammatus'] = {-- Planes                            
		['name'] = 'Mammatus',
		['brand'] = 'Plane',
		['model'] = 'mammatus',
		['price'] = 20000000,
		['category'] = 'planes',
		['hash'] = `0x97E55D11`,
		['shop'] = 'air',
    },
-- 1of1
	['rygdiscovery'] = {-- Bailey
		['name'] = 'Land Rover TD5 ',
		['brand'] = 'Land Rover',
		['model'] = 'rygdiscovery',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `rygdiscovery`,
		['shop'] = '1of1',
    },
	['rmodgtr'] = { -- Danny
		['name'] = 'GTR R35 Widebody',
		['brand'] = 'GTR',
		['model'] = 'rmodgtr',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `rmodgtr`,
		['shop'] = '1of1',
	},	
	['lamks'] = { -- Danny
		['name'] = 'Lamborghini Aventador KS',
		['brand'] = 'Lamborghini',
		['model'] = 'lamks',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `lamks`,
		['shop'] = '1of1',
    },
	['starone'] = { -- Ching
		['name'] = 'Polestar',
		['brand'] = 'Polestar',
		['model'] = 'starone',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `starone`,
		['shop'] = '1of1',
    },	
	['gxa90'] = { -- Ching
		['name'] = 'A90 Supra',
		['brand'] = 'Supra',
		['model'] = 'gxa90',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `gxa90`,
		['shop'] = '1of1',
    },	
	['pulsarhr'] = { -- Ching
		['name'] = 'Nissan Pulsar GTI WB',
		['brand'] = 'Nissan',
		['model'] = 'pulsarhr',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `pulsarhr`,
		['shop'] = '1of1',
    },		
	['rx8hachi'] = { -- Ching
		['name'] = 'Mazda RX8',
		['brand'] = 'Mazda',
		['model'] = 'rx8hachi',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `rx8hachi`,
		['shop'] = '1of1',
    },		
	['rs666'] = { -- Storm
		['name'] = 'Audi RS666',
		['brand'] = 'Audi',
		['model'] = 'rs666',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `rs666`,
		['shop'] = '1of1',
    },		
	['lcbeast'] = { -- Danny
		['name'] = 'Land Cruiser Beast',
		['brand'] = 'Land Cruiser',
		['model'] = 'lcbeast',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `lcbeast`,
		['shop'] = '1of1',
    },		
	['nc1'] = { -- Reggie
		['name'] = 'Acura NSX',
		['brand'] = 'Acura',
		['model'] = 'nc1',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `nc1`,
		['shop'] = '1of1',
    },		
	['skyline'] = { -- Indz
		['name'] = 'Nissan R34',
		['brand'] = 'Nissan',
		['model'] = 'skyline',
		['price'] = 10,
		['category'] = '1of1',
		['hash'] = `skyline`,
		['shop'] = '1of1',
    },		
}
